name: Dev Branch Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get Maven Build Version
        id: maven-version
        uses: ./.github/actions/get-maven-version

      - name: Display Maven Build Version
        run: echo "Maven project version is ${{ steps.maven-version.outputs.build-version }}"
